### ISSUE TITLE
Update SEO and Meta data for site

### ISSUE THREAD

**Issue by Greeshma2903** [Engicos-Coders-Club/club-official-website#36]
Requires addition of the following:

- [ ] Favicon (icon, apple-icon)
- [ ] Page titles
- [ ] Open graph tags
- [ ] Sitemap
- [ ] Metadata (page descriptions, keywords)

Attached is the club logo to generate Favicon and Open Graph images:
![coders-club-logo-23](https://github.com/Engicos-Coders-Club/club-official-website/assets/70336930/884ed474-f007-47a2-8301-9fc276fc1399)

Once you start working on the issue, please comment for more details on metadata.
